"""add key_numbers_json to query_runs

Revision ID: 33897bde32dc
Revises: 0001
Create Date: 2026-07-03 12:55:11.978400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33897bde32dc'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_runs', sa.Column('key_numbers_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_runs', 'key_numbers_json')
    # ### end Alembic commands ###
